from enum import Enum, auto


class BuildPhase(Enum):
    EARLY_GAME = auto()
    EXPANDING = auto()
    MID_GAME = auto()
    MAXED = auto()


class CameraMode(Enum):
    SCOUT = auto()
    EXPAND = auto()
    DEFEND = auto()
    ARMY = auto()
    ENGAGE = auto()


WORKERS_PER_MINERAL = 2
WORKERS_PER_GAS = 3
MAX_SATURATION_RATIO = 0.9
THREAT_RANGE = 15
ENGAGE_RANGE = 8
BASE_MINERAL_RADIUS = 10

GATEWAY_MINERAL_BASELINE = 4
GATEWAY_PER_BASE = 3
GATEWAY_MINERAL_FLOAT_THRESHOLD = 500
GATEWAY_MINERAL_FLOAT_EXTRA = 2
MAX_GATEWAYS = 16

FORGE_MINERAL_THRESHOLD = 300
UPGRADE_RESOURCE_THRESHOLD = 500

UPGRADE_WEAPONS_PRIORITY = 1
UPGRADE_ARMOR_PRIORITY = 2
UPGRADE_SHIELDS_PRIORITY = 3

T3_UNITS = {
    "Protoss": {
        "COLOSSUS", "CARRIER", "TEMPEST", "MOTHERSHIP", "VOIDRAY", "IMMORTAL",
    },
    "Terran": {
        "BATTLECRUISER", "THOR", "SIEGETANK", "SIEGETANKSIEGED",
        "LIBERATOR", "LIBERATORAG", "BANSHEE", "GHOST", "RAVEN",
    },
    "Zerg": {
        "BROODLORD", "ULTRALISK", "CORRUPTOR", "MUTALISK",
        "LURKER", "VIPER", "SWARMHOSTMP", "INFESTOR",
    },
}
